//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electionapis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_CONSTITUENCIES
    {
        public int ID { get; set; }
        public string STATE_NAME { get; set; }
        public string DISTRICT_NAME { get; set; }
        public Nullable<int> CONSTITUENCY_NUMBER { get; set; }
        public string CONSTITUENCY_NAME { get; set; }
        public string TDP { get; set; }
        public string YSRCP { get; set; }
        public string BJP { get; set; }
        public string OTHERS { get; set; }
        public Nullable<int> WINNER_VOTE { get; set; }
        public Nullable<int> MARGIN_VOTE { get; set; }
        public string SELECTED_CANDIDATE { get; set; }
    }
}
