//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electionapis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EMonk_ProductionEntities : DbContext
    {
        public EMonk_ProductionEntities()
            : base("name=EMonk_ProductionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<ASP_RETRIEVE_CONSISTENCYSS_WINNING_LIST_Result> ASP_RETRIEVE_CONSISTENCYSS_WINNING_LIST(string dISTNAME)
        {
            var dISTNAMEParameter = dISTNAME != null ?
                new ObjectParameter("DISTNAME", dISTNAME) :
                new ObjectParameter("DISTNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ASP_RETRIEVE_CONSISTENCYSS_WINNING_LIST_Result>("ASP_RETRIEVE_CONSISTENCYSS_WINNING_LIST", dISTNAMEParameter);
        }
    }
}
